-- 最小示例（取消注释即可跑）：
-- INSERT INTO public.inventory (product_id, title, on_hand) VALUES
--   ('lana-pods', 'LANA 3 颗装', 500),
--   ('diya-pods', 'DIYA 烟弹', 300)
-- ON CONFLICT (product_id) DO UPDATE
--   SET title = excluded.title,
--       on_hand = excluded.on_hand;
--
-- 整站 SKU 请用：insert_inventory_zh.sql（简体说明 + 全量 UPSERT）
-- 或与 insert_inventory_zh 同步维护的：seed_inventory_all.sql
